services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Charger automatiquement tout ce qui est dans src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']