services:

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ultras_php
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: ultras_nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend/public:/var/www/html/public
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  db:
    image: mariadb:11
    container_name: ultras_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ultras_lions
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ultras_phpmyadmin
    environment:
      PMA_HOSTS: ultras_db
      PMA_PORTS: 3306
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
  
  # node:
  #   image: node:18
  #   container_name: ultras_node
  #   working_dir: /app
  #   volumes:
  #     - ./assets:/app/assets
  #     - ./public/build:/app/public/build
  #     - ./webpack.config.js:/app/webpack.config.js
  #     - ./:/app
  #   command: ["tail", "-f", "/dev/null"]

volumes:
  db_data:
